apiVersion: v1
kind: Service
metadata:
  name: stateful-web
  namespace: troubleshooting-lab
  labels:
    app: stateful-web
    incident: statefulset-pv
spec:
  clusterIP: None
  selector:
    app: stateful-web
  ports:
    - name: http
      port: 80
      targetPort: http
