apiVersion: v1
kind: Service
metadata:
  name: image-pull-demo
  namespace: troubleshooting-lab
spec:
  selector:
    app: image-pull-demo

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

  type: ClusterIP
