fullnameOverride: monitoring

grafana:
  enabled: true

  adminPassword: admin123

  service:
    type: ClusterIP

  persistence:
    enabled: false

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL

    datasources:
      enabled: true

prometheus:
  enabled: true

  prometheusSpec:
    retention: 6h

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi

    storageSpec: {}

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

  alertmanagerSpec:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

    storage: {}

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true

  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 256Mi

defaultRules:
  create: true
