apiVersion: apps/v1
kind: Deployment
metadata:
  name: unauthorized-client
  namespace: network-policy-lab
  labels:
    app: unauthorized-client
spec:
  replicas: 1

  selector:
    matchLabels:
      app: unauthorized-client

  template:
    metadata:
      labels:
        app: unauthorized-client
        tier: test

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: client
          image: curlimages/curl:8.12.1
          imagePullPolicy: IfNotPresent

          command:
            - /bin/sh
            - -c
            - sleep infinity

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: 10m
              memory: 16Mi

            limits:
              cpu: 50m
              memory: 32Mi
