apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-demo-config
  namespace: observability-demo
  labels:
    app: observability-demo
data:
  APP_VERSION: "1.0.0"
  APP_ENVIRONMENT: "kubernetes"
